import Head from "next/head";
import { useEffect, useState } from "react";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { client } from "../utils";

export default function Home({ products }) {
  const [images, setImages] = useState([]);
  const [updatedResult, setUpdatedResult] = useState();
  useEffect(() => {
    setUpdatedResult(
      products.map(async (prop) => {
        const data = new FormData();
        data.append("file", prop.images[0].src);
        data.append("upload_preset", "c_tags");

        try {
          const res = await fetch(
            "https://api.cloudinary.com/v1_1/kizmelvin/image/upload",
            {
              method: "POST",
              body: data,
            }
          );
          const file = await res.json();
          // console.log(file);
          return {
            ...prop,
            images: [
              {
                src: file.url,
              },
            ],
          };
        } catch (error) {
          console.error(error);
        }
      })
    );
  }, [products]);
  console.log(products);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button onClick={() => console.log(updatedResult)}>Load data</button>
      </main>
    </div>
  );
}

export const getServerSideProps = async () => {
  const products = await client.product.fetchAll(); // Fetch product

  return {
    props: {
      products: JSON.parse(JSON.stringify(products)),
    },
  };
};
